package com.macifuinaj.catalog.catalog.service;

import com.macifuinaj.catalog.catalog.dto.ProductRequest;
import com.macifuinaj.catalog.catalog.dto.ProductResponse;
import com.macifuinaj.catalog.catalog.entity.Product;
import com.macifuinaj.catalog.catalog.entity.ProductStatus;
import com.macifuinaj.catalog.catalog.mapper.ProductMapper;
import com.macifuinaj.catalog.catalog.repository.ProductRepository;
import com.macifuinaj.catalog.common.exception.DuplicateProductException;
import com.macifuinaj.catalog.common.exception.ProductNotFoundException;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.mongodb.core.MongoTemplate;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;

    @Mock
    private MongoTemplate mongoTemplate;

    // Use the real mapper so response mapping is exercised too.
    private final ProductMapper productMapper = new ProductMapper();

    private ProductServiceImpl productService;

    private ProductRequest sampleRequest() {
        return new ProductRequest(
                "SKU-1",
                "iPhone",
                "iphone",
                "A phone",
                new BigDecimal("999.9900"),
                "USD",
                ProductStatus.ACTIVE
        );
    }

    private ProductServiceImpl service() {
        if (productService == null) {
            productService = new ProductServiceImpl(
                    productRepository,
                    productMapper,
                    mongoTemplate
            );
        }

        return productService;
    }

    @Test
    void createPersistsProductAndReturnsResponse() {

        ProductRequest request = sampleRequest();

        when(productRepository.existsBySku("SKU-1"))
                .thenReturn(false);

        when(productRepository.existsBySlug("iphone"))
                .thenReturn(false);

        when(productRepository.save(any(Product.class)))
                .thenAnswer(invocation -> {
                    Product product = invocation.getArgument(0);

                    // Simulates the ID generated by MongoDB on insert.
                    product.setId("68c35e7ca14cbf72660ad543");

                    return product;
                });

        ProductResponse response = service().create(request);

        assertThat(response.sku()).isEqualTo("SKU-1");
        assertThat(response.id()).isNotNull();

        ArgumentCaptor<Product> captor =
                ArgumentCaptor.forClass(Product.class);

        verify(productRepository).save(captor.capture());

        assertThat(captor.getValue().getId()).isNotNull();
        assertThat(captor.getValue().getStatus())
                .isEqualTo(ProductStatus.ACTIVE);
    }

    @Test
    void createFailsOnDuplicateSku() {

        when(productRepository.existsBySku("SKU-1"))
                .thenReturn(true);

        assertThatThrownBy(() -> service().create(sampleRequest()))
                .isInstanceOf(DuplicateProductException.class)
                .hasMessageContaining("SKU-1");

        verify(productRepository, never()).save(any());
    }

    @Test
    void createFailsOnDuplicateSlug() {

        when(productRepository.existsBySku("SKU-1"))
                .thenReturn(false);

        when(productRepository.existsBySlug("iphone"))
                .thenReturn(true);

        assertThatThrownBy(() -> service().create(sampleRequest()))
                .isInstanceOf(DuplicateProductException.class)
                .hasMessageContaining("iphone");

        verify(productRepository, never()).save(any());
    }

    @Test
    void getByIdThrowsWhenMissing() {

        String id = "68c35e7ca14cbf72660ad544";

        when(productRepository.findById(id))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() -> service().getById(id))
                .isInstanceOf(ProductNotFoundException.class);
    }

    @Test
    void updateModifiesExistingProduct() {

        String id = "68c35e7ca14cbf72660ad545";

        Product existing = new Product();

        existing.setId(id);
        existing.setSku("SKU-1");
        existing.setSlug("iphone");
        existing.setName("Old");
        existing.setPrice(new BigDecimal("1.0000"));
        existing.setCurrency("USD");
        existing.setStatus(ProductStatus.DRAFT);

        when(productRepository.findById(id))
                .thenReturn(Optional.of(existing));

        when(productRepository.save(any(Product.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        ProductRequest request = sampleRequest();

        ProductResponse response = service().update(id, request);

        assertThat(response.name()).isEqualTo("iPhone");
        assertThat(response.status())
                .isEqualTo(ProductStatus.ACTIVE);
    }

    @Test
    void updateThrowsWhenMissing() {

        String id = "68c35e7ca14cbf72660ad546";

        when(productRepository.findById(id))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() -> service().update(id, sampleRequest()))
                .isInstanceOf(ProductNotFoundException.class);
    }

    @Test
    void deleteRemovesExistingProduct() {

        String id = "68c35e7ca14cbf72660ad547";

        when(productRepository.existsById(id))
                .thenReturn(true);

        service().delete(id);

        verify(productRepository).deleteById(id);
    }

    @Test
    void deleteThrowsWhenMissing() {

        String id = "68c35e7ca14cbf72660ad548";

        when(productRepository.existsById(id))
                .thenReturn(false);

        assertThatThrownBy(() -> service().delete(id))
                .isInstanceOf(ProductNotFoundException.class);

        verify(productRepository, never())
                .deleteById(any());
    }
}